coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
        only_pulls: true

flag_management:
  individual_flags:
    - name: unity-6000.0
      carryforward: true
    - name: unity-6000.3
      carryforward: true