name: 🚀 Release (Preview)
on:
  workflow_dispatch:

jobs:
  create-preview-release:
    name: Pre Release
    uses: ./.github/workflows/release-template.yml
    with:
      blockPullRequestRelease: false
      blockReleaseCommit: true
    secrets: inherit

