name: 🚀 Release
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'

jobs:
  create-release:
    name: Release
    uses: mygamedevtools/unity-package-ci/.github/workflows/versioning-semver.yml@main
    with:
      unitypackage-export-method: PackageExporter.ExportPackage
    secrets: inherit
