name: 🚀 Release
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'

jobs:
  create-release:
    name: Release
    uses: ./.github/workflows/release-template.yml
    with:
      packagePath: "Packages/com.mygamedevtools.scene-loader"
    secrets:
      githubToken: ${{ secrets.GH_TOKEN }}
