name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test in ${{ matrix.testMode }}
    # TODO: Replace once Unity fixes the issues with the tests on linux: https://github.com/mygamedevtools/scene-loader/issues/18
    # runs-on: ubuntu-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        project-path:
          - ./
        testMode:
          - playmode
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.project-path }}/Library
          key: Library-${{ matrix.project-path }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          # TODO: Remove once Unity fixes the issues with the tests on linux: https://github.com/mygamedevtools/scene-loader/issues/18
          customImage: 'unityci/editor:windows-2022.3.2f1-base-1'
          projectPath: ${{ matrix.project-path }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
          coverageOptions: 'generateAdditionalMetrics;assemblyFilters:+MyGameDevTools.SceneLoading'
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: PlayMode
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ steps.tests.outputs.coveragePath }}/**/*.xml